// AUTO-GENERATED by ATS v2.1 — safe to delete and regenerate
// SOURCE: apps/visual-editor/src/editor-form/utils/ai-utils.ts
// SOURCE_HASH: acf10af22f25
// GENERATED_AT: 2026-06-02
// NOTE: readFileAsBase64 wraps FileReader (a DOM side effect). Exercised
// here against jsdom's FileReader — kept in the suite because the parse
// logic (data-URL regex → { mediaType, data }) is worth locking down.
import { describe, it, expect } from "vitest";
import { readFileAsBase64 } from "../../editor-form/utils/ai-utils";

describe("readFileAsBase64", () => {
  it("resolves the file's media type and base64 payload", async () => {
    const file = new File(["hello"], "note.txt", { type: "text/plain" });
    const { mediaType, data } = await readFileAsBase64(file);
    expect(mediaType).toBe("text/plain");
    // data is the base64 body after the "data:...;base64," prefix
    expect(atob(data)).toBe("hello");
  });

  it("reports the declared media type for image files", async () => {
    const file = new File([new Uint8Array([1, 2, 3])], "p.png", {
      type: "image/png",
    });
    const { mediaType, data } = await readFileAsBase64(file);
    expect(mediaType).toBe("image/png");
    expect(typeof data).toBe("string");
    expect(data.length).toBeGreaterThan(0);
  });
});
