// AUTO-GENERATED by ATS v2.1 — safe to delete and regenerate
// SOURCE: apps/visual-editor/src/editor-form/utils/preview-route.ts
// SOURCE_HASH: d6bf2152c5ab
// GENERATED_AT: 2026-06-02
import { describe, it, expect } from "vitest";
import {
  isUnhydratedPath,
  buildPreviewUrl,
  buildStaticPreviewUrl,
} from "../../editor-form/utils/preview-route";

describe("isUnhydratedPath", () => {
  it("is true for paths containing a ':' param", () => {
    expect(isUnhydratedPath("/products/:handle")).toBe(true);
  });

  it("is false for concrete paths", () => {
    expect(isUnhydratedPath("/products/blue-tshirt")).toBe(false);
    expect(isUnhydratedPath("/")).toBe(false);
  });

  it("is false for undefined", () => {
    expect(isUnhydratedPath(undefined)).toBe(false);
  });
});

describe("buildPreviewUrl", () => {
  it("appends the path and ?editor=true to the origin", () => {
    expect(buildPreviewUrl("http://localhost:4344", "/about")).toBe(
      "http://localhost:4344/about?editor=true",
    );
  });

  it("falls back to '/' for an unhydrated (':') path", () => {
    expect(buildPreviewUrl("http://localhost:4344", "/products/:handle")).toBe(
      "http://localhost:4344/?editor=true",
    );
  });

  it("falls back to '/' when path is undefined", () => {
    expect(buildPreviewUrl("http://localhost:4344", undefined)).toBe(
      "http://localhost:4344/?editor=true",
    );
  });
});

describe("buildStaticPreviewUrl", () => {
  it("targets the static-preview route with editor + templateId params", () => {
    expect(buildStaticPreviewUrl("http://localhost:4344", "policy-privacy")).toBe(
      "http://localhost:4344/editor-preview/static?editor=true&templateId=policy-privacy",
    );
  });

  it("includes the lang param when a language is provided", () => {
    expect(
      buildStaticPreviewUrl("http://localhost:4344", "policy-privacy", "fr"),
    ).toBe(
      "http://localhost:4344/editor-preview/static?editor=true&templateId=policy-privacy&lang=fr",
    );
  });
});
