// AUTO-GENERATED by ATS v2.1 — safe to delete and regenerate
// SOURCE: apps/visual-editor/src/editor-form/utils/schema-converter.ts
// SOURCE_HASH: 9da7be542c1f
// GENERATED_AT: 2026-06-02
import { describe, it, expect } from "vitest";
import { convertSchemaToFormSchema } from "../../editor-form/utils/schema-converter";

describe("convertSchemaToFormSchema", () => {
  it("maps each schema entry's known fields into the form schema", () => {
    const input = {
      title: {
        type: "text",
        label: "Title",
        placeholder: "Enter title",
        default: "Hello",
      },
    };
    expect(convertSchemaToFormSchema(input)).toEqual({
      title: {
        type: "text",
        label: "Title",
        options: undefined,
        min: undefined,
        max: undefined,
        step: undefined,
        placeholder: "Enter title",
        fields: undefined,
        default: "Hello",
      },
    });
  });

  it("carries numeric constraints and select options through", () => {
    const input = {
      columns: { type: "number", label: "Columns", min: 1, max: 6, step: 1 },
      align: {
        type: "select",
        label: "Align",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
        ],
      },
    };
    const out = convertSchemaToFormSchema(input);
    expect(out.columns.min).toBe(1);
    expect(out.columns.max).toBe(6);
    expect(out.columns.step).toBe(1);
    expect(out.align.options).toHaveLength(2);
  });

  it("preserves nested object-array `fields`", () => {
    const input = {
      faqs: {
        type: "objectArray",
        label: "FAQs",
        fields: { q: { type: "text" }, a: { type: "richText" } },
      },
    };
    expect(convertSchemaToFormSchema(input).faqs.fields).toEqual({
      q: { type: "text" },
      a: { type: "richText" },
    });
  });

  it("returns an empty form schema for an empty input", () => {
    expect(convertSchemaToFormSchema({})).toEqual({});
  });

  it("converts every key in the schema", () => {
    const out = convertSchemaToFormSchema({
      a: { type: "text" },
      b: { type: "text" },
      c: { type: "text" },
    });
    expect(Object.keys(out)).toEqual(["a", "b", "c"]);
  });
});
