// AUTO-GENERATED by ATS v2.1 — safe to delete and regenerate
// SOURCE: apps/visual-editor/src/editor-form/utils/utils.ts
// SOURCE_HASH: 593d3a9d5634
// GENERATED_AT: 2026-06-02
import { describe, it, expect } from "vitest";
import { cn } from "../../editor-form/utils/utils";

describe("cn", () => {
  it("joins multiple class strings", () => {
    expect(cn("a", "b")).toBe("a b");
  });

  it("drops falsy values (conditional classes)", () => {
    expect(cn("a", false, null, undefined, "b")).toBe("a b");
  });

  it("supports object syntax (clsx) for conditional classes", () => {
    expect(cn({ active: true, hidden: false })).toBe("active");
  });

  it("merges conflicting tailwind utilities — last wins (tailwind-merge)", () => {
    expect(cn("px-2", "px-4")).toBe("px-4");
    expect(cn("text-sm", "text-lg")).toBe("text-lg");
  });

  it("returns an empty string for no/empty input", () => {
    expect(cn()).toBe("");
    expect(cn("", null, false)).toBe("");
  });
});
